### ISSUE TITLE
[ Detail ] 사진을 배경으로 하는 레큐 노트 클릭 시, 모달에서 사진 줌되는 이슈

### ISSUE THREAD

**Issue by Arooming** [Team-Lecue/Lecue-Client#230]
## 💚 어떤 기능인가요?
- 사진을 배경으로 하는 레큐 노트 클릭 시, 모달에서 사진 줌되는 이슈
- 기존에 넣은대로 잘 뜨는 노트가 있고, 이상하게 줌인되는 노트가 있음! 확인이 필요함

## ✅ To Dos

- [x] 사진을 배경으로 하는 레큐 노트 클릭 시, 모달에서 사진 줌되는 이슈 해결

**Comment by jungwoo3490** [comment]
확인했습니다!!!!!
